version: "3"
services:
    sdc:
        image: streamsets/datacollector
        ports:
            - 18630:18630
        container_name: sdc
        restart: on-failure
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data:rw
        ports:
            - 9200:9200
            - 9300:9300
volumes:
  esdata1:
    driver: local